from datetime import date
from pydantic import BaseModel, Field
from typing import Optional


class Farm(BaseModel):
    """
    A single Solar Farm with all its details
    """

    id: int
    name: str
    capacity_kw: float
    address: str
    city: str
    state: str
    zip: str

    class Config:
        orm_mode = True


class DailyEnergy(BaseModel):
    """
    A daily total of energy generated by a solar farm
    """

    id: Optional[int] = Field(default=None)
    farm_id: int
    date: date
    kw_total: float

    class Config:
        orm_mode = True


class MaxMonth(BaseModel):
    """
    A response to convey the month in which a farm generated the most energy
    """

    year: int
    month: int
    month_total: float
